spring.application.name=sansaweigh

spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=sansaweigh

spring.data.redis.host=localhost
spring.data.redis.port=6379

app.external-scale-api.url=http://localhost:3000

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
